// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: potechi.proto
#ifndef GRPC_potechi_2eproto__INCLUDED
#define GRPC_potechi_2eproto__INCLUDED

#include "potechi.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace potechi {

class Potechi final {
 public:
  static constexpr char const* service_full_name() {
    return "potechi.Potechi";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>> Vote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>>(VoteRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>> AsyncVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>>(AsyncVoteRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>> PrepareAsyncVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>>(PrepareAsyncVoteRaw(context, cq));
    }
    virtual ::grpc::Status Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::potechi::CountingReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::potechi::CountingReply>> AsyncCounting(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::potechi::CountingReply>>(AsyncCountingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::potechi::CountingReply>> PrepareAsyncCounting(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::potechi::CountingReply>>(PrepareAsyncCountingRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Vote(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::potechi::VoteRequest,::potechi::VoteReply>* reactor) = 0;
      #else
      virtual void Vote(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::potechi::VoteRequest,::potechi::VoteReply>* reactor) = 0;
      #endif
      virtual void Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>* VoteRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>* AsyncVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::potechi::VoteRequest, ::potechi::VoteReply>* PrepareAsyncVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::potechi::CountingReply>* AsyncCountingRaw(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::potechi::CountingReply>* PrepareAsyncCountingRaw(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>> Vote(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>>(VoteRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>> AsyncVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>>(AsyncVoteRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>> PrepareAsyncVote(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>>(PrepareAsyncVoteRaw(context, cq));
    }
    ::grpc::Status Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::potechi::CountingReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::potechi::CountingReply>> AsyncCounting(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::potechi::CountingReply>>(AsyncCountingRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::potechi::CountingReply>> PrepareAsyncCounting(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::potechi::CountingReply>>(PrepareAsyncCountingRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Vote(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::potechi::VoteRequest,::potechi::VoteReply>* reactor) override;
      #else
      void Vote(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::potechi::VoteRequest,::potechi::VoteReply>* reactor) override;
      #endif
      void Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Counting(::grpc::ClientContext* context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>* VoteRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>* AsyncVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::potechi::VoteRequest, ::potechi::VoteReply>* PrepareAsyncVoteRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::potechi::CountingReply>* AsyncCountingRaw(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::potechi::CountingReply>* PrepareAsyncCountingRaw(::grpc::ClientContext* context, const ::potechi::CountingRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Vote_;
    const ::grpc::internal::RpcMethod rpcmethod_Counting_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Vote(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::potechi::VoteReply, ::potechi::VoteRequest>* stream);
    virtual ::grpc::Status Counting(::grpc::ServerContext* context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Vote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Vote() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Vote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Vote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::potechi::VoteReply, ::potechi::VoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVote(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::potechi::VoteReply, ::potechi::VoteRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Counting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Counting() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Counting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Counting(::grpc::ServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCounting(::grpc::ServerContext* context, ::potechi::CountingRequest* request, ::grpc::ServerAsyncResponseWriter< ::potechi::CountingReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Vote<WithAsyncMethod_Counting<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Vote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Vote() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::potechi::VoteRequest, ::potechi::VoteReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->Vote(context); }));
    }
    ~ExperimentalWithCallbackMethod_Vote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Vote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::potechi::VoteReply, ::potechi::VoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::potechi::VoteRequest, ::potechi::VoteReply>* Vote(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::potechi::VoteRequest, ::potechi::VoteReply>* Vote(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Counting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Counting() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::potechi::CountingRequest, ::potechi::CountingReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::potechi::CountingRequest* request, ::potechi::CountingReply* response) { return this->Counting(context, request, response); }));}
    void SetMessageAllocatorFor_Counting(
        ::grpc::experimental::MessageAllocator< ::potechi::CountingRequest, ::potechi::CountingReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::potechi::CountingRequest, ::potechi::CountingReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Counting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Counting(::grpc::ServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Counting(
      ::grpc::CallbackServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Counting(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Vote<ExperimentalWithCallbackMethod_Counting<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Vote<ExperimentalWithCallbackMethod_Counting<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Vote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Vote() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Vote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Vote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::potechi::VoteReply, ::potechi::VoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Counting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Counting() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Counting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Counting(::grpc::ServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Vote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Vote() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Vote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Vote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::potechi::VoteReply, ::potechi::VoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVote(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Counting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Counting() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Counting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Counting(::grpc::ServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCounting(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Vote : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Vote() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context) { return this->Vote(context); }));
    }
    ~ExperimentalWithRawCallbackMethod_Vote() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Vote(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::potechi::VoteReply, ::potechi::VoteRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Vote(
      ::grpc::CallbackServerContext* /*context*/)
    #else
    virtual ::grpc::experimental::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Vote(
      ::grpc::experimental::CallbackServerContext* /*context*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Counting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Counting() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Counting(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Counting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Counting(::grpc::ServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Counting(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Counting(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Counting : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Counting() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::potechi::CountingRequest, ::potechi::CountingReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::potechi::CountingRequest, ::potechi::CountingReply>* streamer) {
                       return this->StreamedCounting(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Counting() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Counting(::grpc::ServerContext* /*context*/, const ::potechi::CountingRequest* /*request*/, ::potechi::CountingReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCounting(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::potechi::CountingRequest,::potechi::CountingReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Counting<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Counting<Service > StreamedService;
};

}  // namespace potechi


#endif  // GRPC_potechi_2eproto__INCLUDED
